CREATE USER 'nanoeagleA'@'localhost' IDENTIFIED BY 'admin';
CREATE SCHEMA MUSICDB_A;
GRANT ALL PRIVILEGES ON MUSICDB_A . * TO 'nanoeagleA'@'localhost';
FLUSH PRIVILEGES;
USE MUSICDB_A;

CREATE USER 'nanoeagleB'@'localhost' IDENTIFIED BY 'admin';
CREATE SCHEMA MUSICDB_B;
GRANT ALL PRIVILEGES ON MUSICDB_B . * TO 'nanoeagleB'@'localhost';
FLUSH PRIVILEGES;
USE MUSICDB_B;